/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#001e2f",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "primary-container": "#0ea5e9",
        "primary-fixed": "#c9e6ff",
        "surface-tint": "#006591",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#001e2b",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-surface-variant": "#3e4850",
        "on-secondary-container": "#005b78",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#c0e8ff",
        "secondary-container": "#7ed4fd",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bec8d2",
        "primary-fixed-dim": "#89ceff",
        "inverse-primary": "#89ceff",
        "error": "#ba1a1a",
        "tertiary": "#50616b",
        "surface-dim": "#d8dadc",
        "tertiary-fixed": "#d3e5f1",
        "on-error": "#ffffff",
        "on-primary-container": "#003751",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#384953",
        "primary": "#006591",
        "on-secondary-fixed-variant": "#004d66",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#7bd1fa",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#0c1e26",
        "outline": "#6e7881",
        "tertiary-fixed-dim": "#b7c9d5",
        "on-primary": "#ffffff",
        "secondary": "#006686",
        "on-primary-fixed-variant": "#004c6e",
        "on-tertiary-container": "#25353e",
        "tertiary-container": "#8c9ea9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      "spacing": {
        "section-gap-mobile": "64px",
        "section-gap-desktop": "120px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-lg": "24px"
      },
      "fontFamily": {
        "label-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["30px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}